### ISSUE TITLE
pip secion of environment gets serialized as a list (no bullets)

### ISSUE THREAD

**Issue by gabrielelanaro** [uchida/ansible-miniconda-role#2]
The pip section doesn't get serialized as a bulleted list, but as a json list like in this example. I think this can be fixed by using to_nice_yaml instead.

That seems to be different to what is produced by conda env export.

```
dependencies:
- cloudpickle=0.1.1=py35_0
- flask=0.10.1=py35_1
- flask-cors=2.1.2=py35_0
- gunicorn=19.1.0=py35_0
- h5py=2.6.0=np110py35_1
- hdf5=1.8.16=0
- heapdict=1.0.0=py35_0
- joblib=0.9.4=py35_0
- jsonschema=2.4.0=py35_0
- nltk=3.2.1=py35_0
- numpy=1.11.0=py35_1
- pandas=0.17.0=np110py35_0
- psycopg2=2.6.1=py35_1
- py=1.4.31=py35_0
- pyyaml=3.11=py35_1
- scikit-learn=0.17.1=np111py35_0
- scipy=0.17.0=np111py35_2
- sqlalchemy=1.0.12=py35_0
- sqlite=3.13.0=0
- yaml=0.1.6=0
- pip: [flask-restful==0.3.5, /var/www/recipestore/foodlab, jwt==0.3.2, pyasn1==0.1.9,
    pycrypto==2.6.1, requests-cache==0.4.12, sqlalchemy-utils==0.32.1]
```

**Comment by gabrielelanaro** [comment]
actually this doesnt seem to cause a problem

**Comment by uchida** [comment]
Thank you for reporting, I think no reason not to use more human readable yaml.
The commit 4e9ab2c, use `to_nice_yaml` instead of `to_yaml` was added.

**Comment by uchida** [comment]
conda env export uses [yaml.dump(d, default_flow_style=False)](https://github.com/conda/conda-env/blob/develop/conda_env/env.py#L156), so `to_yaml(default_flow_style=False)` in a60391 instead of using `to_nice_yaml`
